### ISSUE TITLE
How to transform code gadgets into their symbolic representations?

### ISSUE THREAD

**Issue by x56981973** [CGCL-codes/VulDeePecker#3]
Do you use some automatic tools or just do it manually?

**Comment by VulDeePecker** [comment]
The process of transforming code gadgets into their symbolic representations is automatic. Please see the paper "VulDeePecker: A Deep Learning-Based System for Vulnerability Detection" for details.

**Comment by hrshy0629** [comment]
How to map user-defined variables to symbolic names  in the one-to-one fashion? Do you use some automatic tools or just do it manually?

**Comment by VulDeePecker** [comment]
It is done automatically. We realize it by ourselves.
